 const userActionConstants =({
    GOOGLE_SIGNIN_START:'GOOGLE_SIGNIN_START',
    SIGNIN_SUCCESS:'SIGNIN_SUCCESS',
    SIGNIN_FAILED:'SIGNIN_FAILED',
    EMAIL_SIGNIN_START:'EMAIL_SIGNIN_START',
    CHECK_USER_SESSION:'CHECK_USER_SESSION',
    SIGNOUT_START:'SIGNOUT_START',
    SIGNOUT_SUCCESS:'SIGNOUT_SUCCESS',
    SIGNOUT_FAILED:'SIGNOUT_FAILED',
    SIGNUP_SUCCESS:'SIGNUP_SUCCESS',
    SIGNUP_STARTED:'SIGNUP_STARTED',
    SIGNUP_FAILED:'SIGNUP_FAILED'
    
})
export default userActionConstants